### ISSUE TITLE
[Fastlane] ARCHIVE FAILED (xcodebuild)

### ISSUE THREAD

**Issue by paxful-ios** [castle/castle-ios#61]
`Castle.io` integrated via Swift Package Manager.
The app can be build directly from Xcode without any problem, but the same app cannot be build via CI/CD (GitLab+Fastlane).
```
** ARCHIVE FAILED **


The following build commands failed:
▸ Compiling FBLPromise+All.m
	CompileSwift normal armv7
	CompileSwift normal arm64
	CompileSwift normal armv7
	CompileSwift normal arm64
	SwiftCodeGeneration normal armv7
	SwiftCodeGeneration normal arm64
	CompileSwift normal armv7
	CompileSwift normal arm64
	CompileC /Users/username/paxapp-ios/build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/PAXAPP/IntermediateBuildFilesPath/Castle.build/Staging_Alpha-iphoneos/Castle.build/Objects-normal/armv7/Castle.o /Users/username/paxapp-ios/build/DerivedData/SourcePackages/checkouts/castle-ios/Castle/Public/Castle.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(9 failures)
▸ Compiling UIViewController+CASScreen.m
▸ Compiling CastleConfiguration.m
▸ Linking FBLPromises.o
▸ Compiling Castle.m

❌  /Users/username/paxapp-ios/build/DerivedData/SourcePackages/checkouts/castle-ios/Castle/Public/Castle.m:26:9: module 'Highwind' not found

@import Highwind;
 ~~~~~~~^~~~~~~~

▸ Compiling CASUtils.m
[17:16:34]: Exit status: 65
```

**Comment by aalekz** [comment]
Hey @paxful-ios,

Thanks for describing the issue. Would it be possible for you to provide some more information? Specifically the xcodebuild command that is used to build the app in CI? If you don't want to share it publicly here maybe you can email me at alex@castle.io?

**Comment by paxful-ios** [comment]
Hey @aalekz 
Here is the `xcodebuild` command:
```
$ set -o pipefail && xcodebuild -workspace PAXAPP.xcworkspace -scheme PAXAPP -configuration Staging_Alpha -derivedDataPath build/DerivedData -destination 'generic/platform=iOS' -archivePath build/Build/PAXAPP\ 2021-06-03\ 12.01.51.xcarchive -allowProvisioningUpdates clean archive | tee /Users/ec2-user/builds/DenTwuxp/0/mobile/paxapp-ios/build/Logs/PAXAPP-PAXAPP.log | xcpretty
```

**Comment by aalekz** [comment]
I was able to reproduce the issue on a gitlab instance using their CI tooling. I was however successful in fixing the issue with the following, simple, config:

```
stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project Castle-SwiftPM.xcodeproj -scheme Castle-SwiftPM | xcpretty
    - xcodebuild -project Castle-SwiftPM.xcodeproj -scheme Castle-SwiftPM -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5' | xcpretty -s
    - xcodebuild test -project Castle-SwiftPM.xcodeproj -scheme Castle-SwiftPM -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5' | xcpretty -s
  tags:
    - ios_14-5
    - xcode_12-5
    - osx_11-2
```

The trick here being to include `xcodebuild -project Castle-SwiftPM.xcodeproj -scheme Castle-SwiftPM -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5' | xcpretty -s`.

I'll do some additional tests using fastlane as well to emulate your environment, will let you know what I find.
